default_stages: [push]
fail_fast: true
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [ commit ]
        args: [--profile=black]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        stages: [ commit ]
        additional_dependencies: ['click==8.0.4']